<#
Deploys Claude Code managed settings as a JSON file.

Intune: Devices > Scripts and remediations > Platform scripts > Add (Windows 10 and later).
  Run this script using the logged on credentials: No
  Run script in 64 bit PowerShell Host: Yes

Claude Code reads C:\Program Files\ClaudeCode\managed-settings.json at startup
and treats it as a managed policy source. Edit the JSON below to change the
deployed settings; see https://code.claude.com/docs/en/settings for available keys.

NOTE: This script is generated by conjure emit-policy --regime hipaa.
The forceLoginOrgUUID value MUST be replaced with your organization's UUID
before deploying. See https://code.claude.com/docs/en/settings for details.
Compliance disclaimer: this configuration reduces non-compliant output risks
but does not make your project compliant. Engage your compliance officer.
#>

$ErrorActionPreference = 'Stop'

$dir = Join-Path $env:ProgramFiles 'ClaudeCode'
New-Item -ItemType Directory -Path $dir -Force | Out-Null

$json = @'
{
  "permissions": {
    "disableBypassPermissionsMode": "disable",
    "deny": [
      "Read(~/.aws/credentials)",
      "Read(~/.ssh/**)"
    ]
  },
  "allowManagedPermissionRulesOnly": true,
  "forceLoginOrgUUID": "REPLACE_WITH_ORG_UUID",
  "sandbox": {
    "enabled": true,
    "failIfUnavailable": true,
    "allowUnsandboxedCommands": false,
    "filesystem": {
      "denyRead": ["~/.aws", "~/.aws/credentials", "~/.ssh"],
      "denyWrite": []
    },
    "network": {
      "allowedDomains": []
    }
  }
}
'@

$path = Join-Path $dir 'managed-settings.json'
[System.IO.File]::WriteAllText($path, $json, (New-Object System.Text.UTF8Encoding($false)))
Write-Output "Wrote $path"
Write-Output "Verify: open Claude Code and run /status -- confirm managed policy source is active"
